# Generated by Django 4.2 on 2025-04-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price for this service', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If checked, this feature will be automatically included'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Base')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='price_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_order', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
