# Generated by Django 4.2 on 2025-03-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Starting price for this service', max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Base')], default='fixed', max_length=20)),
                ('price_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='quotes.service')),
            ],
            options={
                'ordering': ['service', 'order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceEstimate',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='quoted_amount',
            new_name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='project_description',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New Request'), ('reviewing', 'Under Review'), ('estimated', 'Estimate Provided'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Project Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='quote_requests', to='quotes.servicefeature'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='service',
            field=models.ForeignKey(default=258, on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='quotes.service'),
            preserve_default=False,
        ),
    ]
